
version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~
    steps:
      - run:
          name: Generate static website
          command: hugo
      - run:
          name: Push to S3 bucket
          command: cd public/ && aws s3 sync . s3://lukayeh-hugo.com
      - run:
          name: Invalidate Distribution 
          command: aws cloudfront create-invalidation --distribution-id=E2ABXXWA8SYGVO --paths "/*" > /dev/null